name: Deploy Docker Image from Docker Hub (Self-Hosted Runner)

on:
  workflow_run:
    workflows: ["Node.js CI with Docker Build and Publish"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout Repository (Optional)
        uses: actions/checkout@v4

      - name: Pull Docker Image from Docker Hub
        run: docker pull oussama871/order-service:latest


      - name: Stop and Remove Existing Docker Container (Windows PowerShell)
        shell: powershell
        run: |
          $container = docker ps -q -f "name=myorderapp"
          if ($container) {
            docker stop myorderapp
            docker rm myorderapp
          }
          else {
            Write-Host "No existing container named 'myorderapp' found."
          }

      - name: Run Docker Container
        run: |
          docker run -d --name myorderapp -p 4000:4000 oussama871/order-service:latest
